name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md
    - name: PHPUnit (php-actions)
      # You may pin to the exact commit or the version.
      # uses: php-actions/phpunit@1789d1964b1bfda259b1cb42a72b65299c2cae35
      uses: php-actions/phpunit@v4
      with:
        # What version of PHPUnit to use
        # version: # optional, default is composer
        # What version of PHP to use
        php_version: '8.3'
        # Space separated list of extensions to configure with the PHP build
        # php_extensions: # optional
        # Path to a vendored phpunit/ binary
        # vendored_phpunit_path: # optional
        # Configuration file location
        # configuration: # optional
        # Memory limit
        # memory_limit: # optional
        # Path to bootstrap file
        # bootstrap: # optional
        # Filter which tests to run
        # filter: # optional
        # Specify a testsuite to run
        # testsuite: # optional
        # Only runs tests from the specified group(s)
        # group: # optional
        # Exclude tests from the specified group(s)
        # exclude_group: # optional
        # Only search for test in files with specified suffix(es)
        # test_suffix: # optional
        # Path to directory to whitelist for code coverage analysis
        # whitelist: # optional
        # Extra arguments to pass to the phpunit binary
        # args: # optional
          

    # - name: Run test suite
    #   run: composer run-script test
